### rootapi
@rootAPI= http://localhost:8000/api/v1
@categoryAPI= http://localhost:8000/api/v1/category


### create new admin
    POST {{rootAPI}}/admin
    Content-Type: application/json

    {
    "fName": "Ashish",
    "lName": "Dhimal",
    "phone":"12345",
    "password": "asshhk",
    "email": "a@gmail.com",
    "address": ""
    }



### POST CATEGORY
POST {{rootAPI}}/category
Content-Type: application/json

{
    "title": "Table"
}

###GET CATEGORY

GET  {{rootAPI}}/category

Content-Type: application/json

{
    "title": "Home Application"
}