### rootapi
@rootAPI= http://localhost:8000/api/v1
@categoryAPI= http://localhost:8000/api/v1/category


### create new admin
    POST {{rootAPI}}/admin
    Content-Type: application/json

    {
    "fName": "Ashish",
    "lName": "Dhimal",
    "phone":"12345",
    "password": "asshhk",
    "email": "a@gmail.com",
    "address": ""
    }



### POST CATEGORY
POST {{rootAPI}}/category
Content-Type: application/json

{
    "title": "home"
}

###GET CATEGORY

GET  {{rootAPI}}/category

Content-Type: application/json

{
    "title": "Home Application"
}

###update category

PUT {{rootAPI}}/category
Content-Type: application/json

{
   "_id":"64c3d8f37410c3ffc78031aa",
   "title":"dfgsdfddddddds" ,
   "status":"active"
}

###
 POST {{rootAPI}}/admin/sign-in
    Content-Type: application/json

    {
    
    "password": "asshhk",
    "email": "a@gmail.com",
    }